### ISSUE TITLE
no missing values but with "ValueError: array must not contain infs or NaNs"

### ISSUE THREAD

**Issue by liym9** [qlu-lab/SUPERGNOVA#12]
I am trying to run my own data on SUPERGNOVA, 
however, I get the following error when testing:

Preparing files for analysis...
Calculating LD scores...
49351 SNPs included in our analysis...
Calculating heritability...
The genome-wide heritability of the first trait is 0.0196689057368004.
The genome-wide heritability of the second trait is -0.011096917527349101.
Calculating phenotypic correlation...
Traceback (most recent call last):
  File "supergnova.py", line 93, in <module>
    pipeline(parser.parse_args())
  File "supergnova.py", line 63, in pipeline
    pheno_corr, pheno_corr_var = pheno(gwas_snps, ld_scores, N1, N2, h_1, h_2)
  File "F:\SUPERGNOVA_Github\SUPERGNOVA\pheno.py", line 33, in pheno
    lm = linear_model.LinearRegression().fit(pd.DataFrame(l), pd.DataFrame(z_xy), sample_weight=w)
  File "F:\python\lib\site-packages\sklearn\linear_model\_base.py", line 569, in fit
    linalg.lstsq(X, y)
  File "F:\python\lib\site-packages\scipy\linalg\basic.py", line 1146, in lstsq
    a1 = _asarray_validated(a, check_finite=check_finite)
  File "F:\python\lib\site-packages\scipy\_lib\_util.py", line 293, in _asarray_validated
    a = toarray(a)
  File "F:\python\lib\site-packages\numpy\lib\function_base.py", line 489, in asarray_chkfinite
    "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs

I have cecked my data, and  no missing values in my GWAS summary data. but I don't know how to solve this problem.  I would be very grateful if you could help me to know what is causing this.

Thanks.

**Comment by theopoliss** [comment]
Hi, there may not appear to be missing values in your GWAS summary data, but this issue may arise from subtleties in the data that may not be apparent as missing or infinite values. Here is a previously resolved issue that may help: https://github.com/qlu-lab/SUPERGNOVA/issues/3.
